// Generated by tools/generateCookingMask.cjs. Edit the mask, then regenerate.
export const COOKING_MASK_REGIONS = {
  "CLOSE": {
    "x": 1408,
    "y": 163,
    "width": 83,
    "height": 85
  },
  "BASE_PREVIOUS": {
    "x": 105,
    "y": 770,
    "width": 133,
    "height": 140
  },
  "BASE_NEXT": {
    "x": 249,
    "y": 770,
    "width": 136,
    "height": 141
  },
  "INGREDIENT_PREVIOUS": {
    "x": 1353,
    "y": 402,
    "width": 120,
    "height": 111
  },
  "INGREDIENT_NEXT": {
    "x": 1354,
    "y": 531,
    "width": 124,
    "height": 109
  },
  "FLAME": {
    "x": 631,
    "y": 855,
    "width": 97,
    "height": 97
  },
  "HEAT_MINUS": {
    "x": 480,
    "y": 845,
    "width": 130,
    "height": 118
  },
  "HEAT_PLUS": {
    "x": 753,
    "y": 845,
    "width": 130,
    "height": 118
  },
  "MATE_WATER": {
    "x": 934,
    "y": 843,
    "width": 136,
    "height": 124
  },
  "BASE_1": {
    "x": 87,
    "y": 456,
    "width": 137,
    "height": 143
  },
  "BASE_2": {
    "x": 236,
    "y": 456,
    "width": 137,
    "height": 143
  },
  "BASE_3": {
    "x": 87,
    "y": 611,
    "width": 137,
    "height": 143
  },
  "BASE_4": {
    "x": 236,
    "y": 611,
    "width": 137,
    "height": 143
  },
  "INGREDIENT_1": {
    "x": 1183,
    "y": 229,
    "width": 137,
    "height": 144
  },
  "INGREDIENT_2": {
    "x": 1183,
    "y": 381,
    "width": 137,
    "height": 143
  },
  "INGREDIENT_3": {
    "x": 1183,
    "y": 532,
    "width": 137,
    "height": 143
  },
  "INGREDIENT_4": {
    "x": 1183,
    "y": 682,
    "width": 137,
    "height": 143
  },
  "OVEN": {
    "x": 436,
    "y": 440,
    "width": 671,
    "height": 374
  },
  "MATE": {
    "x": 812,
    "y": 196,
    "width": 292,
    "height": 219
  },
  "ORDER_1": {
    "x": 156,
    "y": 205,
    "width": 171,
    "height": 160
  },
  "ORDER_2": {
    "x": 348,
    "y": 205,
    "width": 171,
    "height": 161
  },
  "ORDER_3": {
    "x": 537,
    "y": 205,
    "width": 171,
    "height": 161
  },
  "READY": {
    "x": 1106,
    "y": 835,
    "width": 282,
    "height": 140
  }
} as const
